#
# December 19, 2013
# The author disclaims copyright to this source code.
#

all: cronprint.exe test.exe

dbell-amal.obj: dbell-amal.c doorbell.h
	cl /nologo /c  dbell-amal.c 

test.exe: dbell-amal.obj
	cl  /EHsc /nologo test.cpp dbell-amal.obj

cronprint.exe: dbell-amal.obj
	cl /nologo cronprint.c dbell-amal.obj

clean:
	del *.exe *.obj